/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene-processed.gltf --transform
Author: Bullatich (https://sketchfab.com/bullatich)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/xyz-school-coursework-highpoly-porsche-singer-62213d5302e64feca76d2bff400b0769
Title: XYZ School Coursework: HighPoly Porsche Singer
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Car(props) {
  const { nodes, materials } = useGLTF('/scene-processed-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.wheel_fr004_TIRES001_0.geometry} material={materials['TIRES.001']} />
          <mesh geometry={nodes.wheel_fr004_TIRES001_0_1.geometry} material={materials['TIRES.001']} />
          <mesh geometry={nodes.wheel_fr004_TIRES001_0_2.geometry} material={materials['TIRES.001']} />
          <mesh geometry={nodes.wheel_fr004_TIRES001_0_3.geometry} material={materials['TIRES.001']} />
          <mesh geometry={nodes.wheel_fr004_CAR_PAINT001_0.geometry} material={materials['CAR_PAINT.001']} />
          <mesh geometry={nodes.wheel_fr004_BRAKES_0.geometry} material={materials.BRAKES} />
          <mesh geometry={nodes.wheel_fr004_TIRES_0.geometry} material={materials.TIRES} />
          <mesh geometry={nodes.wheel_fr004_RED001_0.geometry} material={materials['RED.001']} />
          <mesh geometry={nodes.wheel_fr001_TIRES001_0.geometry} material={materials['TIRES.001']} />
          <mesh geometry={nodes.wheel_fr001_TIRES001_0_1.geometry} material={materials['TIRES.001']} />
          <mesh geometry={nodes.wheel_fr001_TIRES001_0_2.geometry} material={materials['TIRES.001']} />
          <mesh geometry={nodes.wheel_fr001_TIRES001_0_3.geometry} material={materials['TIRES.001']} />
          <mesh geometry={nodes.wheel_fr001_CAR_PAINT001_0.geometry} material={materials['CAR_PAINT.001']} />
          <mesh geometry={nodes.wheel_fr001_BRAKES_0.geometry} material={materials.BRAKES} />
          <mesh geometry={nodes.wheel_fr001_TIRES_0.geometry} material={materials.TIRES} />
          <mesh geometry={nodes.wheel_fr001_RED001_0.geometry} material={materials['RED.001']} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.bottom_BLACK_ROUGH_0.geometry} material={materials.TIRES} position={[0, 0, 0.01]} />
          <mesh geometry={nodes.wing_BLACK_0.geometry} material={materials.BLACK} />
          <mesh geometry={nodes.windows_BLACK_0.geometry} material={materials.BLACK} />
          <mesh geometry={nodes.windows_GLASS_0.geometry} material={materials.GLASS} />
          <mesh geometry={nodes.windows_CHROME_0.geometry} material={materials.CHROME} />
          <mesh geometry={nodes.trunk_CAR_PAINT_0.geometry} material={materials.CAR_PAINT} />
          <mesh geometry={nodes.trunk_BLACK_ROUGH_0.geometry} material={materials.TIRES} />
          <mesh geometry={nodes.top_spoiler_CAR_PAINT_0.geometry} material={materials.CAR_PAINT} />
          <mesh geometry={nodes.top_spoiler_BLACK_0.geometry} material={materials.BLACK} />
          <mesh geometry={nodes.top_spoiler_GLASS_0.geometry} material={materials.GLASS} />
          <mesh geometry={nodes.skirt_CARBON_0.geometry} material={materials.CARBON} />
          <mesh geometry={nodes.rubber_BLACK001_0.geometry} material={materials['BLACK.001']} />
          <mesh geometry={nodes.roof_CAR_PAINT_0.geometry} material={materials.CAR_PAINT} />
          <mesh geometry={nodes.rear_lights_RED_0.geometry} material={materials.material} />
          <mesh geometry={nodes.rear_lights_CHROME_0.geometry} material={materials.CHROME} />
          <mesh geometry={nodes.rear_lights_RED_GLASS_0.geometry} material={materials.RED_GLASS} />
          <mesh geometry={nodes.rear_lights_YELLOW_0.geometry} material={materials.YELLOW} />
          <mesh geometry={nodes.rear_lights_BLACK_0.geometry} material={materials.BLACK} />
          <mesh geometry={nodes.rear_bumper_CAR_PAINT_0.geometry} material={materials.CAR_PAINT} />
          <mesh geometry={nodes.rear_bumper_CARBON_0.geometry} material={materials.CARBON} />
          <mesh geometry={nodes.rear_bumper_BLACK_ROUGH_0.geometry} material={materials.TIRES} />
          <mesh geometry={nodes._rear_splitter_CARBON_0.geometry} material={materials.CARBON} />
          <mesh geometry={nodes.air_intake_CARBON_0.geometry} material={materials.CARBON} />
          <mesh geometry={nodes.air_intake_BLACK_ROUGH_0.geometry} material={materials.TIRES} />
          <mesh geometry={nodes.air_intake_side_CARBON_0.geometry} material={materials.CARBON} />
          <mesh geometry={nodes.body_CAR_PAINT_0.geometry} material={materials.CAR_PAINT} />
          <mesh geometry={nodes.bumper_rear2_CAR_PAINT_0.geometry} material={materials.CAR_PAINT} />
          <mesh geometry={nodes.door_CAR_PAINT_0.geometry} material={materials.CAR_PAINT} />
          <mesh geometry={nodes.exhaust_GRAY_0.geometry} material={materials.GRAY} />
          <mesh geometry={nodes.Fenders_CAR_PAINT_0.geometry} material={materials.CAR_PAINT} />
          <mesh geometry={nodes.Fenders_CHROME_0.geometry} material={materials.CHROME} />
          <mesh geometry={nodes.front_bumper_BLACK_ROUGH_0.geometry} material={materials.TIRES} />
          <mesh geometry={nodes.front_bumper_CAR_PAINT_0.geometry} material={materials.CAR_PAINT} />
          <mesh geometry={nodes.front_bumper_CARBON_0.geometry} material={materials.CARBON} />
          <mesh geometry={nodes.fuel_filler_flap_CHROME_0.geometry} material={materials.CHROME} />
          <mesh geometry={nodes.handle_CAR_PAINT_0.geometry} material={materials.CAR_PAINT} />
          <mesh geometry={nodes.handle_CHROME_0.geometry} material={materials.CHROME} />
          <mesh geometry={nodes.handle_BLACK_ROUGH_0.geometry} material={materials.TIRES} />
          <mesh geometry={nodes.headlights_up_GLASS_0.geometry} material={materials.GLASS} />
          <mesh geometry={nodes.headlights_up_CHROME_0.geometry} material={materials.CHROME} />
          <mesh geometry={nodes.headlights_up_Material002_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.hood_CAR_PAINT_0.geometry} material={materials.CAR_PAINT} />
          <mesh geometry={nodes.hood_BLACK_ROUGH_0.geometry} material={materials.TIRES} />
          <mesh geometry={nodes.mirrors_BLACK_ROUGH_0.geometry} material={materials.TIRES} />
          <mesh geometry={nodes.mirrors_CAR_PAINT_0.geometry} material={materials.CAR_PAINT} />
          <mesh geometry={nodes.mirrors_Material_0.geometry} material={materials.Material} />
          <mesh geometry={nodes.body001_CHROME_0.geometry} material={materials.CHROME} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.seats_LEATHER_0.geometry} material={materials.LEATHER} />
          <mesh geometry={nodes.seats_BLACK_0.geometry} material={materials.BLACK} />
          <mesh geometry={nodes.seats_CHROME_0.geometry} material={materials.CHROME} />
          <mesh geometry={nodes.seats_BLACK_ROUGH_0.geometry} material={materials.TIRES} />
          <mesh geometry={nodes.seats_RED001_0.geometry} material={materials['RED.001']} />
          <mesh geometry={nodes.steering_wheel_LEATHER_0.geometry} material={materials.LEATHER} />
          <mesh geometry={nodes.steering_wheel_BLACK_ROUGH_0.geometry} material={materials.TIRES} />
          <mesh geometry={nodes.steering_wheel_CARBON_0.geometry} material={materials.CARBON} />
          <mesh geometry={nodes.steering_column_BLACK_ROUGH_0.geometry} material={materials.TIRES} />
          <mesh geometry={nodes.steering_column_CHROME_0.geometry} material={materials.CHROME} />
          <mesh geometry={nodes.tunnel_CARBON_0.geometry} material={materials.CARBON} />
          <mesh geometry={nodes.tunnel_LEATHER_0.geometry} material={materials.LEATHER} />
          <mesh geometry={nodes.tunnel_BLACK_ROUGH_0.geometry} material={materials.TIRES} />
          <mesh geometry={nodes.tunnel_GRAY_0.geometry} material={materials.GRAY} />
          <mesh geometry={nodes.duct_CARBON_0.geometry} material={materials.CARBON} />
          <mesh geometry={nodes.pedals_GRAY_0.geometry} material={materials.GRAY} />
          <mesh geometry={nodes.pedals_CARBON_0.geometry} material={materials.CARBON} />
          <mesh geometry={nodes.gauge_BLACK_ROUGH_0.geometry} material={materials.TIRES} />
          <mesh geometry={nodes.gauge_CHROME_0.geometry} material={materials.CHROME} />
          <mesh geometry={nodes.gauge_WHITE_0.geometry} material={materials.WHITE} />
          <mesh geometry={nodes.doors_int_BLACK_ROUGH_0.geometry} material={materials.TIRES} />
          <mesh geometry={nodes.doors_int_CAR_PAINT_0.geometry} material={materials.CAR_PAINT} />
          <mesh geometry={nodes.doors_int_CARBON_0.geometry} material={materials.CARBON} />
          <mesh geometry={nodes.doors_int_CHROME_0.geometry} material={materials.CHROME} />
          <mesh geometry={nodes.doors_int_LEATHER_0.geometry} material={materials.LEATHER} />
          <mesh geometry={nodes.dash_top_BLACK_ROUGH_0.geometry} material={materials.TIRES} />
          <mesh geometry={nodes.dash_bottom__BLACK_ROUGH_0.geometry} material={materials.TIRES} />
          <mesh geometry={nodes.dash_bottom__BLACK_0.geometry} material={materials.BLACK} />
          <mesh geometry={nodes.dash_bottom__LEATHER_0.geometry} material={materials.LEATHER} />
          <mesh geometry={nodes.dash_bottom__GRAY_0.geometry} material={materials.GRAY} />
          <mesh geometry={nodes.dash_bottom__CHROME_0.geometry} material={materials.CHROME} />
          <mesh geometry={nodes.body_amplifier_GRAY_0.geometry} material={materials.GRAY} />
          <mesh geometry={nodes.body_amplifier_CHROME_0.geometry} material={materials.CHROME} />
          <mesh geometry={nodes.body_amplifier_LEATHER_0.geometry} material={materials.LEATHER} />
          <mesh geometry={nodes.footrest_GRAY_0.geometry} material={materials.GRAY} />
          <mesh geometry={nodes.gear_shift_lever_LEATHER_0.geometry} material={materials.LEATHER} />
          <mesh geometry={nodes.gear_shift_lever_BLACK_ROUGH_0.geometry} material={materials.TIRES} />
          <mesh geometry={nodes.gear_shift_lever_GRAY_0.geometry} material={materials.GRAY} />
          <mesh geometry={nodes.gear_shift_lever_CHROME_0.geometry} material={materials.CHROME} />
          <mesh geometry={nodes.mirror_int_BLACK_ROUGH_0.geometry} material={materials.TIRES} />
          <mesh geometry={nodes.mirror_int_Material_0.geometry} material={materials.Material} />
          <mesh geometry={nodes.cabin_CAR_PAINT_0.geometry} material={materials.CAR_PAINT} />
          <mesh geometry={nodes.cabin_CARBON_0.geometry} material={materials.CARBON} />
          <mesh geometry={nodes.cabin_BLACK_ROUGH_0.geometry} material={materials.TIRES} />
          <mesh geometry={nodes.dash_bottom_001_CHROME_0.geometry} material={materials.CHROME} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene-processed-transformed.glb')
